import { Geist, Geist_Mono, Sour_Gummy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/MenuBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sour_gummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sour_gummy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
